package com.gpaer.model;

import java.util.Date;

public class GPALog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpalog.id
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpalog.sid
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpalog.ip
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpalog.delaytime
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    private Integer delaytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpalog.time
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpalog.url
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpalog.server
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    private String server;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpalog.id
     *
     * @return the value of gpalog.id
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpalog.id
     *
     * @param id the value for gpalog.id
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpalog.sid
     *
     * @return the value of gpalog.sid
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpalog.sid
     *
     * @param sid the value for gpalog.sid
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpalog.ip
     *
     * @return the value of gpalog.ip
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpalog.ip
     *
     * @param ip the value for gpalog.ip
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpalog.delaytime
     *
     * @return the value of gpalog.delaytime
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public Integer getDelaytime() {
        return delaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpalog.delaytime
     *
     * @param delaytime the value for gpalog.delaytime
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public void setDelaytime(Integer delaytime) {
        this.delaytime = delaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpalog.time
     *
     * @return the value of gpalog.time
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpalog.time
     *
     * @param time the value for gpalog.time
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpalog.url
     *
     * @return the value of gpalog.url
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpalog.url
     *
     * @param url the value for gpalog.url
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpalog.server
     *
     * @return the value of gpalog.server
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public String getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpalog.server
     *
     * @param server the value for gpalog.server
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public void setServer(String server) {
        this.server = server;
    }
}