package com.gpaer.dao;

import com.gpaer.model.GPALog;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GPALogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpalog
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    @Delete({
        "delete from gpalog",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpalog
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    @Insert({
        "insert into gpalog (id, sid, ",
        "ip, delaytime, time, ",
        "url, server)",
        "values (#{id,jdbcType=INTEGER}, #{sid,jdbcType=VARCHAR}, ",
        "#{ip,jdbcType=VARCHAR}, #{delaytime,jdbcType=INTEGER}, #{time,jdbcType=TIMESTAMP}, ",
        "#{url,jdbcType=VARCHAR}, #{server,jdbcType=VARCHAR})"
    })
    int insert(GPALog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpalog
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    @InsertProvider(type=GPALogSqlProvider.class, method="insertSelective")
    int insertSelective(GPALog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpalog
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    @Select({
        "select",
        "id, sid, ip, delaytime, time, url, server",
        "from gpalog",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="sid", property="sid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ip", property="ip", jdbcType=JdbcType.VARCHAR),
        @Result(column="delaytime", property="delaytime", jdbcType=JdbcType.INTEGER),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="server", property="server", jdbcType=JdbcType.VARCHAR)
    })
    GPALog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpalog
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    @UpdateProvider(type=GPALogSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GPALog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpalog
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    @Update({
        "update gpalog",
        "set sid = #{sid,jdbcType=VARCHAR},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "delaytime = #{delaytime,jdbcType=INTEGER},",
          "time = #{time,jdbcType=TIMESTAMP},",
          "url = #{url,jdbcType=VARCHAR},",
          "server = #{server,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GPALog record);
}