package com.gpaer.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.gpaer.model.GPALog;

public class GPALogSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpalog
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public String insertSelective(GPALog record) {
        BEGIN();
        INSERT_INTO("gpalog");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getSid() != null) {
            VALUES("sid", "#{sid,jdbcType=VARCHAR}");
        }
        
        if (record.getIp() != null) {
            VALUES("ip", "#{ip,jdbcType=VARCHAR}");
        }
        
        if (record.getDelaytime() != null) {
            VALUES("delaytime", "#{delaytime,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            VALUES("time", "#{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUrl() != null) {
            VALUES("url", "#{url,jdbcType=VARCHAR}");
        }
        
        if (record.getServer() != null) {
            VALUES("server", "#{server,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpalog
     *
     * @mbggenerated Sat Jun 24 14:10:58 CST 2017
     */
    public String updateByPrimaryKeySelective(GPALog record) {
        BEGIN();
        UPDATE("gpalog");
        
        if (record.getSid() != null) {
            SET("sid = #{sid,jdbcType=VARCHAR}");
        }
        
        if (record.getIp() != null) {
            SET("ip = #{ip,jdbcType=VARCHAR}");
        }
        
        if (record.getDelaytime() != null) {
            SET("delaytime = #{delaytime,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            SET("time = #{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUrl() != null) {
            SET("url = #{url,jdbcType=VARCHAR}");
        }
        
        if (record.getServer() != null) {
            SET("server = #{server,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}